POST http://localhost:5000/api/services
Content-Type: application/json

{
  "name": "algum serviço",
  "description": "alguma descrição",
  "price": 1000,
  "image": "image url"
}

###

GET http://localhost:5000/api/services

###

GET http://localhost:5000/api/services/6472a871b60806b2e42a5d59

###

DELETE http://localhost:5000/api/services/6472a871b60806b2e42a5d59
 
###

PUT http://localhost:5000/api/services/6472a871b60806b2e42a5d59
Content-Type: application/json

{
  "name": "nome",
  "description": "descrição",
  "price": 1000,
  "image": "url da imagem"
}

###

POST http://localhost:5000/api/parties
Content-Type: application/json

{
  "title": "eventoooo doiss",
  "description": "segunda festa",
  "author": "kevsss",
  "budget": 999999999,
  "image": "imagem",
  "services": [
    {
      "name": "algum serviço 1",
      "description": "alguma descrição",
      "price": 4000,
      "image": "image url"
    },
    {
      "name": "algum serviço 2",
      "description": "alguma descrição",
      "price": 3000,
      "image": "image url"
    },
    {
      "name": "serviço exclusivo de kevvv",
      "description": "descrição dO eventO",
      "price": 120000,
      "image": "URL dA imagemmm"
    }
  ]
}

###

GET http://localhost:5000/api/parties

###

GET http://localhost:5000/api/parties/id

###

DELETE http://localhost:5000/api/parties/id

###

PUT http://localhost:5000/api/parties/647552b4b2fc9d03ace00f2d
Content-Type: application/json

{
  "title": "eventoooo updated",
  "description": "segunda festa updateeeddd",
  "author": "kevsss",
  "budget": 999899999,
  "image": "imagem",
  "services": [
    {
      "name": "algum serviço 1",
      "description": "alguma descrição",
      "price": 4000,
      "image": "image url"
    },
    {
      "name": "algum serviço 2",
      "description": "alguma descrição",
      "price": 3000,
      "image": "image url"
    },
    {
      "name": "serviço exclusivo de kevvv",
      "description": "descrição dO eventO",
      "price": 120000,
      "image": "URL dA imagemmm"
    }
  ]
}