POST http://localhost:5000/api/parties
Content-Type: application/json

{
  "title": "eventoooo doiss",
  "description": "segunda festa",
  "author": "kevsss",
  "budget": 999999999,
  "image": "imagem",
  "services": [
    {
      "name": "algum serviço 1",
      "description": "alguma descrição",
      "price": 4000,
      "image": "image url"
    },
    {
      "name": "algum serviço 2",
      "description": "alguma descrição",
      "price": 3000,
      "image": "image url"
    },
    {
      "name": "serviço exclusivo de kevvv",
      "description": "descrição dO eventO",
      "price": 120000,
      "image": "URL dA imagemmm"
    }
  ]
}